# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageQueryUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImageQuery(object):
    def setupUi(self, ImageQuery):
        ImageQuery.setObjectName("ImageQuery")
        ImageQuery.resize(700, 550)
        self.centralwidget = QtWidgets.QWidget(ImageQuery)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 47, 13))
        self.label_4.setObjectName("label_4")
        self.lineEdit_image_data = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_image_data.setGeometry(QtCore.QRect(80, 60, 431, 20))
        self.lineEdit_image_data.setObjectName("lineEdit_image_data")
        self.button_browse_image_data = QtWidgets.QPushButton(self.centralwidget)
        self.button_browse_image_data.setGeometry(QtCore.QRect(520, 60, 41, 23))
        self.button_browse_image_data.setObjectName("button_browse_image_data")
        self.button_load_image_data = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image_data.setGeometry(QtCore.QRect(570, 60, 111, 23))
        self.button_load_image_data.setObjectName("button_load_image_data")
        self.lineEdit_database = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_database.setGeometry(QtCore.QRect(80, 90, 431, 20))
        self.lineEdit_database.setObjectName("lineEdit_database")
        self.button_browse_database = QtWidgets.QPushButton(self.centralwidget)
        self.button_browse_database.setGeometry(QtCore.QRect(520, 90, 41, 23))
        self.button_browse_database.setObjectName("button_browse_database")
        self.button_save_database = QtWidgets.QPushButton(self.centralwidget)
        self.button_save_database.setGeometry(QtCore.QRect(570, 90, 51, 23))
        self.button_save_database.setObjectName("button_save_database")
        self.button_load_database = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_database.setGeometry(QtCore.QRect(630, 90, 51, 23))
        self.button_load_database.setObjectName("button_load_database")
        self.lineEdit_image = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_image.setGeometry(QtCore.QRect(80, 120, 431, 20))
        self.lineEdit_image.setObjectName("lineEdit_image")
        self.button_browse_image = QtWidgets.QPushButton(self.centralwidget)
        self.button_browse_image.setGeometry(QtCore.QRect(520, 120, 41, 23))
        self.button_browse_image.setObjectName("button_browse_image")
        self.button_query_image = QtWidgets.QPushButton(self.centralwidget)
        self.button_query_image.setGeometry(QtCore.QRect(570, 120, 111, 23))
        self.button_query_image.setObjectName("button_query_image")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 520, 651, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(180, 160, 350, 350))
        self.graphicsView.setObjectName("graphicsView")
        self.button_next = QtWidgets.QPushButton(self.centralwidget)
        self.button_next.setGeometry(QtCore.QRect(580, 300, 75, 51))
        self.button_next.setObjectName("button_next")
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setGeometry(QtCore.QRect(50, 300, 75, 51))
        self.button_back.setObjectName("button_back")
        ImageQuery.setCentralWidget(self.centralwidget)

        self.retranslateUi(ImageQuery)
        QtCore.QMetaObject.connectSlotsByName(ImageQuery)

    def retranslateUi(self, ImageQuery):
        _translate = QtCore.QCoreApplication.translate
        ImageQuery.setWindowTitle(_translate("ImageQuery", "ImageQuery_OpenCV"))
        self.label.setText(_translate("ImageQuery", "Image Query"))
        self.label_2.setText(_translate("ImageQuery", "Image Data"))
        self.label_3.setText(_translate("ImageQuery", "Database"))
        self.label_4.setText(_translate("ImageQuery", "Image"))
        self.button_browse_image_data.setText(_translate("ImageQuery", "..."))
        self.button_load_image_data.setText(_translate("ImageQuery", "Load"))
        self.button_browse_database.setText(_translate("ImageQuery", "..."))
        self.button_save_database.setText(_translate("ImageQuery", "Save"))
        self.button_load_database.setText(_translate("ImageQuery", "Load"))
        self.button_browse_image.setText(_translate("ImageQuery", "..."))
        self.button_query_image.setText(_translate("ImageQuery", "Query"))
        self.button_next.setText(_translate("ImageQuery", "Next"))
        self.button_back.setText(_translate("ImageQuery", "Back"))

